apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: packersmovers
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: packersmovers
      tier: frontend
  template:
    metadata:
      labels:
        app: packersmovers
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: your-docker-image-name:tag
        imagePullPolicy: Always
        ports:
        - containerPort: 80
